[package]
name = "trigger"
edition = "2021"
version = "0.1.0"

[workspace]

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = { version = "0.24", features = ["default"] }
serde = {version = "1.0.203", features = ["derive"]}
serde_json = "1.0.118"
